In [20]:
import pandas as pd
import numpy as np

#### Series with List

In [2]:
list1 = [100,200,300,400]

In [3]:
print(list1)

[100, 200, 300, 400]


In [4]:
s1 = pd.Series(list1)

In [5]:
s1

0    100
1    200
2    300
3    400
dtype: int64

In [6]:
s2 = pd.Series(list1, index = ["A","B","C","D"])

In [7]:
s2

A    100
B    200
C    300
D    400
dtype: int64

In [8]:
s2["A"]

100

In [9]:
s2[0]

100

In [10]:
list2 = [[10,20],[30,40],[50,60]]

In [11]:
s3 = pd.Series(list2)

In [12]:
s3

0    [10, 20]
1    [30, 40]
2    [50, 60]
dtype: object

##### Series with Scalar

In [13]:
# Scalar - 9 

In [14]:
pd.Series(9)

0    9
dtype: int64

In [15]:
pd.Series(9,index =[0,1,2,3,4])

0    9
1    9
2    9
3    9
4    9
dtype: int64

In [16]:
pd.Series(9,index =[0,1,2,3,4], dtype = 'float')

0    9.0
1    9.0
2    9.0
3    9.0
4    9.0
dtype: float64

In [17]:
pd.Series(9,index =[0,1,2,3,4], dtype = 'float32')

0    9.0
1    9.0
2    9.0
3    9.0
4    9.0
dtype: float32

In [21]:
pd.Series(9,index =[0,1,2,3,4], dtype = np.float32)

0    9.0
1    9.0
2    9.0
3    9.0
4    9.0
dtype: float32

#### SCALAR WITH NUMPY ARRAY

In [22]:
ary1 = np.arange(10, 20, 1)

In [23]:
ary1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
pd.Series(ary1)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int32

In [25]:
s1 = "ABCDEFGHIJ"
list(s1)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [26]:
pd.Series(ary1, index = list("ABCDEFGHIJ"))

A    10
B    11
C    12
D    13
E    14
F    15
G    16
H    17
I    18
J    19
dtype: int32

In [29]:
pd.Series([], dtype = "int")

Series([], dtype: int32)

In [31]:
dic1 = {
    
        "A" : 100,
        "B" : 200,
        "C" : 300,
        "D" : 400
}

In [32]:
dic1

{'A': 100, 'B': 200, 'C': 300, 'D': 400}

In [33]:
pd.Series(dic1)

A    100
B    200
C    300
D    400
dtype: int64

In [34]:
pd.Series(dic1,index = ['AA','BB','CC','DD'])

AA   NaN
BB   NaN
CC   NaN
DD   NaN
dtype: float64

In [35]:
pd.Series(dic1, index = ["A","D"])

A    100
D    400
dtype: int64

In [36]:
pd.Series(dic1, index = ["C","A","D","B"])

C    300
A    100
D    400
B    200
dtype: int64

In [38]:
s2 = pd.Series(dic1)

In [39]:
s2

A    100
B    200
C    300
D    400
dtype: int64

In [40]:
s2['C']

300

In [41]:
s2[2]

300

In [42]:
s3 = pd.Series(dic1, index = ["C","A","D","B"])

In [43]:
s3

C    300
A    100
D    400
B    200
dtype: int64

In [44]:
s3['D']

400

In [45]:
s3[2]

400

In [46]:
s3[1:3]

A    100
D    400
dtype: int64

In [48]:
s3["A" : "B"]

A    100
D    400
B    200
dtype: int64

In [50]:
s3[["A","C"]]

A    100
C    300
dtype: int64

In [51]:
s3

C    300
A    100
D    400
B    200
dtype: int64

In [53]:
s4 = pd.Series(dic1, index = ["C1","A1","D1","B1"])

In [54]:
s4

C1   NaN
A1   NaN
D1   NaN
B1   NaN
dtype: float64

In [55]:
s5 = pd.Series(dic1, index = ["C","A","D","B"])

In [56]:
s5

C    300
A    100
D    400
B    200
dtype: int64

In [57]:
s5.index

Index(['C', 'A', 'D', 'B'], dtype='object')

In [59]:
s5.index = [0,1,2,3]

In [60]:
s5

0    300
1    100
2    400
3    200
dtype: int64

In [65]:
ary2 = np.random.randint(10,50,(12,))

In [66]:
ary2

array([34, 16, 19, 48, 28, 38, 42, 35, 17, 24, 43, 31])

In [68]:
s6 = pd.Series(ary2)

In [69]:
s6

0     34
1     16
2     19
3     48
4     28
5     38
6     42
7     35
8     17
9     24
10    43
11    31
dtype: int32

In [71]:
f1 = s6 > 30

In [72]:
f1

0      True
1     False
2     False
3      True
4     False
5      True
6      True
7      True
8     False
9     False
10     True
11     True
dtype: bool

In [73]:
s6[f1]

0     34
3     48
5     38
6     42
7     35
10    43
11    31
dtype: int32

In [75]:
f2 = s6 < 40

In [76]:
s6[f2]

0     34
1     16
2     19
4     28
5     38
7     35
8     17
9     24
11    31
dtype: int32

In [77]:
a1 = np.arange(10,20)

In [78]:
a2 = np.arange(20,30)

In [79]:
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [80]:
a2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
s_a1 = pd.Series(a1)

In [82]:
s_a2 = pd.Series(a2)

In [83]:
s_a1

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int32

In [84]:
s_a2

0    20
1    21
2    22
3    23
4    24
5    25
6    26
7    27
8    28
9    29
dtype: int32

In [86]:
s_result = s_a1 + s_a2

In [87]:
s_result

0    30
1    32
2    34
3    36
4    38
5    40
6    42
7    44
8    46
9    48
dtype: int32

In [88]:
s6

0     34
1     16
2     19
3     48
4     28
5     38
6     42
7     35
8     17
9     24
10    43
11    31
dtype: int32

In [89]:
s6.rank()

0      7.0
1      1.0
2      3.0
3     12.0
4      5.0
5      9.0
6     10.0
7      8.0
8      2.0
9      4.0
10    11.0
11     6.0
dtype: float64

In [90]:
s6.rank(ascending=False)

0      6.0
1     12.0
2     10.0
3      1.0
4      8.0
5      4.0
6      3.0
7      5.0
8     11.0
9      9.0
10     2.0
11     7.0
dtype: float64

In [91]:
s6.sort_values()

1     16
8     17
2     19
9     24
4     28
11    31
0     34
7     35
5     38
6     42
10    43
3     48
dtype: int32

In [93]:
s6.sort_index(ascending=False)

11    31
10    43
9     24
8     17
7     35
6     42
5     38
4     28
3     48
2     19
1     16
0     34
dtype: int32

In [94]:
s6.sort_values(ascending=False)

3     48
10    43
6     42
5     38
7     35
0     34
11    31
4     28
9     24
2     19
8     17
1     16
dtype: int32