In [1]:
import pandas as pd
import numpy as np

In [3]:
X=np.arange(2,20,2)

In [4]:
X

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
pf=PolynomialFeatures()

In [7]:
df1=pd.DataFrame(X)

In [8]:
df1

0
0   2
1   4
2   6
3   8
4  10
5  12
6  14
7  16
8  18

In [10]:
pf.fit(df1)

PolynomialFeatures()

In [13]:
df1poly=pf.transform(df1)

In [14]:
df1poly

array([[  1.,   2.,   4.],
       [  1.,   4.,  16.],
       [  1.,   6.,  36.],
       [  1.,   8.,  64.],
       [  1.,  10., 100.],
       [  1.,  12., 144.],
       [  1.,  14., 196.],
       [  1.,  16., 256.],
       [  1.,  18., 324.]])

In [16]:
pf1=PolynomialFeatures(degree=3)

In [17]:
df1poly1=pf1.fit_transform(df1)

In [18]:
df1poly1

array([[1.000e+00, 2.000e+00, 4.000e+00, 8.000e+00],
       [1.000e+00, 4.000e+00, 1.600e+01, 6.400e+01],
       [1.000e+00, 6.000e+00, 3.600e+01, 2.160e+02],
       [1.000e+00, 8.000e+00, 6.400e+01, 5.120e+02],
       [1.000e+00, 1.000e+01, 1.000e+02, 1.000e+03],
       [1.000e+00, 1.200e+01, 1.440e+02, 1.728e+03],
       [1.000e+00, 1.400e+01, 1.960e+02, 2.744e+03],
       [1.000e+00, 1.600e+01, 2.560e+02, 4.096e+03],
       [1.000e+00, 1.800e+01, 3.240e+02, 5.832e+03]])