#### hey guys let me introduce my self Raj Kulhade and you are seeing my data science repository
#### so enjoy yourself while doing the Data Encoding as i used to enjoy haha lets get started

## Data Encoding

first we are importing the python modules pandas and numpy

In [2]:
import pandas as pd
import numpy as np

we are making a dictionary object as d1 and objects in d1 are Name , Age , City

In [3]:
d1= {
    
    "Name":["A","B","C","D","E"],
    "Age":[25,30,22,28,26],
    "City":["Hyd","Del","Che","Hyd","Vig"]
}

we are now converting it to a Data Frame which is a function of pandas,      pd.Dataframe

In [4]:
dfemp=pd.DataFrame(d1)

In [5]:
dfemp

Name  Age City
0    A   25  Hyd
1    B   30  Del
2    C   22  Che
3    D   28  Hyd
4    E   26  Vig

#### name is ordinal categorical data
#### age is numerical data
#### city is nominal categorical data

#### taking only now City columns

In [6]:
dfemp["City"]

0    Hyd
1    Del
2    Che
3    Hyd
4    Vig
Name: City, dtype: object

#### we are using the function called as get dummies , in get dummies sometime people falls on the dummy trap so just everytime use like Drop_first=True

In [7]:
dfdummy=pd.get_dummies(dfemp["City"])

In [8]:
dfemp

Name  Age City
0    A   25  Hyd
1    B   30  Del
2    C   22  Che
3    D   28  Hyd
4    E   26  Vig

In [9]:
dfencode=pd.concat([dfemp,dfdummy],axis=1)

In [10]:
dfencode

Name  Age City  Che  Del  Hyd  Vig
0    A   25  Hyd    0    0    1    0
1    B   30  Del    0    1    0    0
2    C   22  Che    1    0    0    0
3    D   28  Hyd    0    0    1    0
4    E   26  Vig    0    0    0    1

In [11]:
dfencode.drop("City",axis=1)

Name  Age  Che  Del  Hyd  Vig
0    A   25    0    0    1    0
1    B   30    0    1    0    0
2    C   22    1    0    0    0
3    D   28    0    0    1    0
4    E   26    0    0    0    1

In [12]:
pd.get_dummies(dfemp["City"],prefix="ind")

ind_Che  ind_Del  ind_Hyd  ind_Vig
0        0        0        1        0
1        0        1        0        0
2        1        0        0        0
3        0        0        1        0
4        0        0        0        1

In [13]:
pd.get_dummies(dfemp["City"],drop_first=True)

Del  Hyd  Vig
0    0    1    0
1    1    0    0
2    0    0    0
3    0    1    0
4    0    0    1

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
ohe=OneHotEncoder()

In [16]:
ohe

OneHotEncoder()

In [18]:
ohe.fit(dfemp[["City"]])

OneHotEncoder()

In [19]:
dfemp

Name  Age City
0    A   25  Hyd
1    B   30  Del
2    C   22  Che
3    D   28  Hyd
4    E   26  Vig

In [20]:
dfemp["City"]

0    Hyd
1    Del
2    Che
3    Hyd
4    Vig
Name: City, dtype: object

In [21]:
type(dfemp["City"])

pandas.core.series.Series

In [22]:
dfemp[["City"]]

City
0  Hyd
1  Del
2  Che
3  Hyd
4  Vig

In [23]:
type(dfemp[["City"]])

pandas.core.frame.DataFrame

In [24]:
ohe.fit(dfemp[["City"]])

OneHotEncoder()

In [25]:
ohe.transform(dfemp[["City"]]).toarray()

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
ary1=ohe.transform(dfemp[["City"]]).toarray()

In [27]:
ohe.categories_

[array(['Che', 'Del', 'Hyd', 'Vig'], dtype=object)]

In [28]:
ary1

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
dfohe=pd.DataFrame(ary1,columns=["Che",'Del','Hyd','Viz'])

In [30]:
dfemp

Name  Age City
0    A   25  Hyd
1    B   30  Del
2    C   22  Che
3    D   28  Hyd
4    E   26  Vig

In [31]:
dfohe

Che  Del  Hyd  Viz
0  0.0  0.0  1.0  0.0
1  0.0  1.0  0.0  0.0
2  1.0  0.0  0.0  0.0
3  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  1.0

In [32]:
dfohe1=pd.concat([dfemp,dfohe],axis=1)

In [33]:
dfohe1

Name  Age City  Che  Del  Hyd  Viz
0    A   25  Hyd  0.0  0.0  1.0  0.0
1    B   30  Del  0.0  1.0  0.0  0.0
2    C   22  Che  1.0  0.0  0.0  0.0
3    D   28  Hyd  0.0  0.0  1.0  0.0
4    E   26  Vig  0.0  0.0  0.0  1.0

In [34]:
dfohe1.drop("City",axis=1)

Name  Age  Che  Del  Hyd  Viz
0    A   25  0.0  0.0  1.0  0.0
1    B   30  0.0  1.0  0.0  0.0
2    C   22  1.0  0.0  0.0  0.0
3    D   28  0.0  0.0  1.0  0.0
4    E   26  0.0  0.0  0.0  1.0

### See we have converted every columns of Cateogrical data to numerical Data and we can covert name also using Ordinal encoding as now on you have seen one hot encoder of scikit learn and now we will see ordinal encoder of scikit-Learn 

In [35]:
from sklearn.preprocessing import OrdinalEncoder

In [36]:
oe = OrdinalEncoder()

In [37]:
dfohe1

Name  Age City  Che  Del  Hyd  Viz
0    A   25  Hyd  0.0  0.0  1.0  0.0
1    B   30  Del  0.0  1.0  0.0  0.0
2    C   22  Che  1.0  0.0  0.0  0.0
3    D   28  Hyd  0.0  0.0  1.0  0.0
4    E   26  Vig  0.0  0.0  0.0  1.0

In [42]:
ary2=oe.fit_transform(dfohe1[["Name"]])

In [43]:
ary2

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]])

Lets convert it to DataFrame

In [44]:
encodename=pd.DataFrame(ary2,columns=["Name"])

In [45]:
encodename

Name
0   0.0
1   1.0
2   2.0
3   3.0
4   4.0

lets join our Dfohe1 and encodename

In [46]:
df=pd.concat([dfohe,encodename],axis=1)

In [47]:
df

Che  Del  Hyd  Viz  Name
0  0.0  0.0  1.0  0.0   0.0
1  0.0  1.0  0.0  0.0   1.0
2  1.0  0.0  0.0  0.0   2.0
3  0.0  0.0  1.0  0.0   3.0
4  0.0  0.0  0.0  1.0   4.0

### See now we have converted every Categorical data in Numerical Data,

## If you like encoding tactics dummy,onehotencoder and ordinal encoding 

## Do share us your review

Thankyou for watching this