In [1]:
import pandas as pd
import numpy as np

In [4]:
ary1=np.arange(10,100,10)

In [5]:
from sklearn.model_selection import train_test_split

In [9]:
train_test_split(ary1,test_size=0.20)

[array([30, 70, 40, 10, 90, 50, 60]), array([20, 80])]

In [10]:
#train_test_split(ary1,test_size=0.20,random_state=22) 

[array([40, 30, 70, 10, 80, 50, 60]), array([90, 20])]

In [13]:
#train_test_split(ary1,test_size=0.20,random_state=22,shuffle=False)

[array([10, 20, 30, 40, 50, 60, 70]), array([80, 90])]

In [14]:
train_test_split(ary1,test_size=0.20)

[array([70, 20, 30, 80, 90, 40, 50]), array([60, 10])]

In [15]:
from sklearn.model_selection import KFold

In [18]:
kf=KFold()

In [20]:
objkf=kf.split(ary1)

In [21]:
list(objkf)

[(array([2, 3, 4, 5, 6, 7, 8]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7, 8]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7, 8]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5, 8]), array([6, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8]))]

In [22]:
list(objkf)

[]

In [33]:
objkf1=kf.split(ary1)

In [35]:
for X , y  in objkf1:
    print(X)
    print(y)

[2 3 4 5 6 7 8]
[0 1]
[0 1 4 5 6 7 8]
[2 3]
[0 1 2 3 6 7 8]
[4 5]
[0 1 2 3 4 5 8]
[6 7]
[0 1 2 3 4 5 6 7]
[8]
