In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\admin\Desktop\Pandas\arjun srikant pandas\machine learning dataset\social.csv")

In [3]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
from sklearn.preprocessing import OneHotEncoder

In [5]:
ohe=OneHotEncoder()

In [6]:
ohe.fit(df[["Gender"]])

OneHotEncoder()

In [7]:
ary1=ohe.transform(df[["Gender"]]).toarray()

In [8]:
encode=pd.DataFrame(ary1,columns=["Female","Male"])

In [9]:
encode

Female  Male
0       0.0   1.0
1       0.0   1.0
2       1.0   0.0
3       1.0   0.0
4       0.0   1.0
..      ...   ...
395     1.0   0.0
396     0.0   1.0
397     1.0   0.0
398     0.0   1.0
399     1.0   0.0

[400 rows x 2 columns]

In [10]:
df=pd.concat([df,encode],axis=1)

In [11]:
df.drop("Gender",axis=1,inplace=True)

In [12]:
df.drop("Female",axis=1,inplace=True)

In [13]:
df

User ID  Age  EstimatedSalary  Purchased  Male
0    15624510   19            19000          0   1.0
1    15810944   35            20000          0   1.0
2    15668575   26            43000          0   0.0
3    15603246   27            57000          0   0.0
4    15804002   19            76000          0   1.0
..        ...  ...              ...        ...   ...
395  15691863   46            41000          1   0.0
396  15706071   51            23000          1   1.0
397  15654296   50            20000          1   0.0
398  15755018   36            33000          0   1.0
399  15594041   49            36000          1   0.0

[400 rows x 5 columns]

In [14]:
df.drop("User ID",axis=1)

Age  EstimatedSalary  Purchased  Male
0     19            19000          0   1.0
1     35            20000          0   1.0
2     26            43000          0   0.0
3     27            57000          0   0.0
4     19            76000          0   1.0
..   ...              ...        ...   ...
395   46            41000          1   0.0
396   51            23000          1   1.0
397   50            20000          1   0.0
398   36            33000          0   1.0
399   49            36000          1   0.0

[400 rows x 4 columns]

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
lr=LogisticRegression()

In [17]:
from sklearn.model_selection import KFold,cross_val_score

In [18]:
kf=KFold(n_splits=10)

In [19]:
X=df.drop("Male",axis=1)

In [20]:
y=df["Male"]

In [21]:
lreg=cross_val_score(lr,X,y,cv=kf)

In [22]:
lreg.mean()

0.49000000000000005

In [92]:
from sklearn.tree import DecisionTreeRegressor

In [93]:
dc=DecisionTreeRegressor()

In [94]:
dtr=cross_val_score(dc,X,y,cv=kf)

In [95]:
dtr

array([-0.8011257 , -0.99488491, -1.00501253, -0.99488491, -0.95121951])

In [96]:
dtr.mean()

-0.9494255136120076

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
sc=StandardScaler()

scscore=cross_val_score(sc,X,y,cv=kf)

In [25]:
sc.fit(X)

StandardScaler()

In [26]:
ary1=sc.transform(X)

In [27]:
ary1

array([[-0.93657932, -1.78179743, -1.49004624, -0.74593581],
       [ 1.66838653, -0.25358736, -1.46068138, -0.74593581],
       [-0.32087714, -1.11320552, -0.78528968, -0.74593581],
       ...,
       [-0.52039175,  1.17910958, -1.46068138,  1.34059793],
       [ 0.88695546, -0.15807423, -1.07893824, -0.74593581],
       [-1.36231017,  1.08359645, -0.99084367,  1.34059793]])

In [28]:
lreg=LogisticRegression()

In [29]:
lregscore=cross_val_score(lreg,X,y,cv=kf)

In [31]:
lregscore

array([0.65 , 0.4  , 0.3  , 0.525, 0.45 , 0.625, 0.575, 0.5  , 0.5  ,
       0.375])