In [1]:
import pandas as pd
import numpy as np

In [2]:
text=["Welcome to python Class,Python is OOps Language",
      'I love White dogs',
     "i Live in city Hyderabad city a part of India"]

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
cvec=CountVectorizer()

In [5]:
cvec.fit(text)

CountVectorizer()

In [7]:
cvec.get_feature_names()

['city',
 'class',
 'dogs',
 'hyderabad',
 'in',
 'india',
 'is',
 'language',
 'live',
 'love',
 'of',
 'oops',
 'part',
 'python',
 'to',
 'welcome',
 'white']

In [11]:
cvec.vocabulary_

{'welcome': 15,
 'to': 14,
 'python': 13,
 'class': 1,
 'is': 6,
 'oops': 11,
 'language': 7,
 'love': 9,
 'white': 16,
 'dogs': 2,
 'live': 8,
 'in': 4,
 'city': 0,
 'hyderabad': 3,
 'part': 12,
 'of': 10,
 'india': 5}

In [15]:
ary1=cvec.transform(text).toarray()

In [16]:
ary1

array([[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 2, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [2, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [17]:
from sklearn.feature_extraction.text import TfidfTransformer

In [18]:
tfid=TfidfTransformer()

In [20]:
text_tfidf=tfid.fit_transform(ary1).toarray()

In [22]:
tfid.idf_

array([1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718])

In [21]:
text_tfidf

array([[0.        , 0.31622777, 0.        , 0.        , 0.        ,
        0.        , 0.31622777, 0.31622777, 0.        , 0.        ,
        0.        , 0.31622777, 0.        , 0.63245553, 0.31622777,
        0.31622777, 0.        ],
       [0.        , 0.        , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.57735027],
       [0.63245553, 0.        , 0.        , 0.31622777, 0.31622777,
        0.31622777, 0.        , 0.        , 0.31622777, 0.        ,
        0.31622777, 0.        , 0.31622777, 0.        , 0.        ,
        0.        , 0.        ]])

In [23]:
ary1

array([[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 2, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [2, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0]], dtype=int64)